### PR TITLE
Correct error estimate for OP

### PR DESCRIPTION
**Pull request by hsantila**
The error estimate calculation for the OP python script was fixed

### CODE REVIEW

**Review by jmelcr — CHANGES_REQUESTED** [review]
I'm afraid that the proposed commit does not do what is intended. 
line 109: I think that std (sntandard deviation) is confused with error of the mean and, hence, stem has a different meaning from what I think was intended.
line 156: I looks to me that the OP value is being constantly overwritten each frame (loop at lin 151), but it is not stored

Style improving: line 153 can be written as 
for i,residue in enumerate(op.selection):
which is preferred.

Thank you for the contribution, it's a good start, I'll look at it next week.

**Comment by hsantila** [comment]
Hi,

I'm under the impression that the convention used for deriving the error within NMRlipids is to calculate time averages over single lipids. Those are then used as independent samples, and final value+error estimate are obtained by calculating the average over all the lipids and the standard error of mean (std/sqrt(N) or std/sqrt(N-1) https://en.wikipedia.org/wiki/Standard_error#Standard_error_of_mean_versus_standard_deviation) for that average.

156 does not overwrite anything. I changed the usage of the variable to accumulate the time average for single-lipid order parameters. You can check this by comparing resulting order parameter values with the original code. They should match.

if you look at line 109 the function now returns 3 values: mean, std and stem. Stem is the std divided by the square root of the number of samples, which equals the number of lipids in the system.

I hope this clarifies things :)

**Comment by jmelcr** [comment]
I'll give it a closer look. Thanks.

**Comment by ohsOllila** [comment]
I will merge now, if there comes up something, we will fix later.

**Pull request merged**
